# Ch. 4 Numpy Basics: Arrays and Vectorized Computation

## 1. The NumPy ndarray: A Multidimentional Array Object

In [1]:
import numpy as np

In [3]:
data_source = [[0.9526, -0.246, -0.8856], [0.5639, 0.2379, 0.9104]]

In [4]:
data = np.array(data_source)

In [5]:
data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [6]:
data * 10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [7]:
data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [8]:
data + data

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

In [9]:
data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

### 1) ndarrya 생성하기 

In [12]:
data1 = [6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data1)

In [14]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
arr1.ndim

1

In [30]:
arr2.ndim

2

In [31]:
arr1.shape

(5,)

In [32]:
arr2.shape

(2, 4)

In [33]:
arr1.dtype

dtype('float64')

In [35]:
arr2.dtype

dtype('int64')

In [37]:
arr3 = np.zeros(10)
arr3

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [40]:
print arr3.ndim
print arr3.shape
print arr3.dtype

1
(10,)
float64


In [42]:
arr4 = np.ones(10)
arr4

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [43]:
print arr4.ndim
print arr4.shape
print arr4.dtype

1
(10,)
float64


In [46]:
arr5 = np.zeros((3, 6))
arr5

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [47]:
print arr5.ndim
print arr5.shape
print arr5.dtype

2
(3, 6)
float64


In [52]:
arr6 = np.zeros((2, 3, 4))
arr6

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

- np.empty(shape): 초기화되지 않은 쓰레기 값들로 값이 채워지는 배열을 생성

In [54]:
arr7 = np.empty((2, 3, 2))
arr7

array([[[  0.00000000e+000,   0.00000000e+000],
        [  2.12277289e-314,   2.22853766e-314],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  3.27025026e-309,   6.87991125e-315],
        [ -2.31584192e+077,   8.34402832e-309]]])

In [55]:
print arr7.ndim
print arr7.shape
print arr7.dtype

3
(2, 3, 2)
float64


In [57]:
arr8 = np.arange(15)
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
print arr8.ndim
print arr8.shape
print arr8.dtype

1
(15,)
int64


- np.array는 기본적으로 새로운 ndarray를 생성한다.

In [59]:
arr9 = np.array(arr8)
arr9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
arr9 is arr8

False

In [61]:
arr9 == arr8

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True], dtype=bool)

- np.asarray는 자신이 받은 내용을 변환만 한다.
  - 자신이 받는 내용이 ndarray이면 아무런 일도 하지 않고 받은 ndarray를 그대로 반환한다.

In [62]:
arr10 = np.asarray(arr8)
arr10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
arr10 is arr8

True

In [65]:
original = [1, 2, 3]

In [66]:
arr11 = np.asarray(original)
arr11

array([1, 2, 3])

In [67]:
original

[1, 2, 3]

In [68]:
arr11 is original

False

- np.eye(n)과 np.identity(n)은 n*n 단위행렬을 생성함

In [73]:
arr12 = np.eye(3)
arr12

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [74]:
arr13 = np.identity(3)
arr13

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

- np.ones_like(ndarray), np.zeros_like(ndarray), np.empty_like(ndarray)
  - 모두 입력으로 주어지는 ndarray와 동일한 shape를 가지는 새로운 ndarray 생성함

In [76]:
arr14 = np.ones_like(arr13)
arr14

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [81]:
arr14 is arr13

False

In [78]:
arr15 = np.zeros_like(arr13)
arr15

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [80]:
arr16 = np.empty_like(arr13)
arr16

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])